### ISSUE TITLE
Enumerable not implemented for Ecto.Date

### ISSUE THREAD

**Issue by smithaitufe** [johnnyji/proper_case#6]
I decided to use proper_case in my project. The experience was wonderful. It was very easy to integrate it. I however have an issue.

I am trying to call an api endpoint that returns a json that has field with Ecto.Date type. This is throwing an error.

```
 ** (Protocol.UndefinedError) protocol Enumerable not implemented for #Ecto.Date<2016-12-20>
        (elixir) lib/enum.ex:1: Enumerable.impl_for!/1
        (elixir) lib/enum.ex:116: Enumerable.reduce/3
        (elixir) lib/enum.ex:1627: Enum.reduce/3
        (proper_case) lib/proper_case.ex:14: anonymous fn/2 in ProperCase.to_camel_case/1
        (stdlib) lists.erl:1262: :lists.foldl/3
        (elixir) lib/enum.ex:1184: Enum."-map/2-lists^map/1-0-"/2
        (proper_case) lib/json_encoder/camel_case.ex:2: ProperCase.JSONEncoder.CamelCase.encode_to_iodata!/1
        (phoenix) lib/phoenix/controller.ex:642: Phoenix.Controller.do_render/4
        (portal_api) web/controllers/v1/academic_session_controller.ex:1: PortalApi.V1.AcademicSessionController.ac
tion/2
        (portal_api) web/controllers/v1/academic_session_controller.ex:1: PortalApi.V1.AcademicSessionController.ph
oenix_controller_pipeline/2
        (portal_api) lib/portal_api/endpoint.ex:1: PortalApi.Endpoint.instrument/4
        (portal_api) lib/phoenix/router.ex:261: PortalApi.Router.dispatch/2
        (portal_api) web/router.ex:1: PortalApi.Router.do_call/2
```

Please kindly see to it soon so that I fix this on my project

I also decided to try the demo project that I use to see how easy it could be to integrate proper_case.

The view below results in an error

```
def render("user.json", %{user: user}) do
    %{id: user.id,
      first_name: user.first_name,
      last_name: user.last_name,
      email: user.email,
      encrypted_password: user.encrypted_password,
      inserted_at: user.inserted_at
    }
  end
```
because of the inserted_at field that I introduced.

**Comment by johnnyji** [comment]
@smithaitufe Sorry for taking so long to respond. @expede has submitted a PR that I think will solve your issue :)
